################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../opencv/cvaccum.cpp \
../opencv/cvadapthresh.cpp \
../opencv/cvapprox.cpp \
../opencv/cvcalccontrasthistogram.cpp \
../opencv/cvcalcimagehomography.cpp \
../opencv/cvcalibinit.cpp \
../opencv/cvcalibration.cpp \
../opencv/cvcamshift.cpp \
../opencv/cvcanny.cpp \
../opencv/cvcolor.cpp \
../opencv/cvcondens.cpp \
../opencv/cvcontours.cpp \
../opencv/cvcontourtree.cpp \
../opencv/cvconvhull.cpp \
../opencv/cvconvolve.cpp \
../opencv/cvcorner.cpp \
../opencv/cvcornersubpix.cpp \
../opencv/cvderiv.cpp \
../opencv/cvdistransform.cpp \
../opencv/cvdominants.cpp \
../opencv/cvemd.cpp \
../opencv/cvfeatureselect.cpp \
../opencv/cvfloodfill.cpp \
../opencv/cvfundam.cpp \
../opencv/cvgeometry.cpp \
../opencv/cvhaar.cpp \
../opencv/cvhistogram.cpp \
../opencv/cvhough.cpp \
../opencv/cvimgwarp.cpp \
../opencv/cvkalman.cpp \
../opencv/cvlinefit.cpp \
../opencv/cvlkpyramid.cpp \
../opencv/cvmatchcontours.cpp \
../opencv/cvmoments.cpp \
../opencv/cvmorph.cpp \
../opencv/cvmotempl.cpp \
../opencv/cvoptflowbm.cpp \
../opencv/cvoptflowhs.cpp \
../opencv/cvoptflowlk.cpp \
../opencv/cvpgh.cpp \
../opencv/cvposit.cpp \
../opencv/cvprecomp.cpp \
../opencv/cvpyramids.cpp \
../opencv/cvpyrsegmentation.cpp \
../opencv/cvrotcalipers.cpp \
../opencv/cvsamplers.cpp \
../opencv/cvshapedescr.cpp \
../opencv/cvsmooth.cpp \
../opencv/cvsnakes.cpp \
../opencv/cvsubdivision2d.cpp \
../opencv/cvsumpixels.cpp \
../opencv/cvswitcher.cpp \
../opencv/cvtables.cpp \
../opencv/cvtemplmatch.cpp \
../opencv/cvthresh.cpp \
../opencv/cvundistort.cpp \
../opencv/cvutils.cpp \
../opencv/cxalloc.cpp \
../opencv/cxarithm.cpp \
../opencv/cxarray.cpp \
../opencv/cxcmp.cpp \
../opencv/cxconvert.cpp \
../opencv/cxcopy.cpp \
../opencv/cxdatastructs.cpp \
../opencv/cxdrawing.cpp \
../opencv/cxdxt.cpp \
../opencv/cxerror.cpp \
../opencv/cxjacobieigens.cpp \
../opencv/cxlogic.cpp \
../opencv/cxlut.cpp \
../opencv/cxmathfuncs.cpp \
../opencv/cxmatmul.cpp \
../opencv/cxmatrix.cpp \
../opencv/cxmean.cpp \
../opencv/cxmeansdv.cpp \
../opencv/cxminmaxloc.cpp \
../opencv/cxnorm.cpp \
../opencv/cxouttext.cpp \
../opencv/cxpersistence.cpp \
../opencv/cxprecomp.cpp \
../opencv/cxrand.cpp \
../opencv/cxsumpixels.cpp \
../opencv/cxsvd.cpp \
../opencv/cxtables.cpp \
../opencv/cxutils.cpp 

OBJS += \
./opencv/cvaccum.o \
./opencv/cvadapthresh.o \
./opencv/cvapprox.o \
./opencv/cvcalccontrasthistogram.o \
./opencv/cvcalcimagehomography.o \
./opencv/cvcalibinit.o \
./opencv/cvcalibration.o \
./opencv/cvcamshift.o \
./opencv/cvcanny.o \
./opencv/cvcolor.o \
./opencv/cvcondens.o \
./opencv/cvcontours.o \
./opencv/cvcontourtree.o \
./opencv/cvconvhull.o \
./opencv/cvconvolve.o \
./opencv/cvcorner.o \
./opencv/cvcornersubpix.o \
./opencv/cvderiv.o \
./opencv/cvdistransform.o \
./opencv/cvdominants.o \
./opencv/cvemd.o \
./opencv/cvfeatureselect.o \
./opencv/cvfloodfill.o \
./opencv/cvfundam.o \
./opencv/cvgeometry.o \
./opencv/cvhaar.o \
./opencv/cvhistogram.o \
./opencv/cvhough.o \
./opencv/cvimgwarp.o \
./opencv/cvkalman.o \
./opencv/cvlinefit.o \
./opencv/cvlkpyramid.o \
./opencv/cvmatchcontours.o \
./opencv/cvmoments.o \
./opencv/cvmorph.o \
./opencv/cvmotempl.o \
./opencv/cvoptflowbm.o \
./opencv/cvoptflowhs.o \
./opencv/cvoptflowlk.o \
./opencv/cvpgh.o \
./opencv/cvposit.o \
./opencv/cvprecomp.o \
./opencv/cvpyramids.o \
./opencv/cvpyrsegmentation.o \
./opencv/cvrotcalipers.o \
./opencv/cvsamplers.o \
./opencv/cvshapedescr.o \
./opencv/cvsmooth.o \
./opencv/cvsnakes.o \
./opencv/cvsubdivision2d.o \
./opencv/cvsumpixels.o \
./opencv/cvswitcher.o \
./opencv/cvtables.o \
./opencv/cvtemplmatch.o \
./opencv/cvthresh.o \
./opencv/cvundistort.o \
./opencv/cvutils.o \
./opencv/cxalloc.o \
./opencv/cxarithm.o \
./opencv/cxarray.o \
./opencv/cxcmp.o \
./opencv/cxconvert.o \
./opencv/cxcopy.o \
./opencv/cxdatastructs.o \
./opencv/cxdrawing.o \
./opencv/cxdxt.o \
./opencv/cxerror.o \
./opencv/cxjacobieigens.o \
./opencv/cxlogic.o \
./opencv/cxlut.o \
./opencv/cxmathfuncs.o \
./opencv/cxmatmul.o \
./opencv/cxmatrix.o \
./opencv/cxmean.o \
./opencv/cxmeansdv.o \
./opencv/cxminmaxloc.o \
./opencv/cxnorm.o \
./opencv/cxouttext.o \
./opencv/cxpersistence.o \
./opencv/cxprecomp.o \
./opencv/cxrand.o \
./opencv/cxsumpixels.o \
./opencv/cxsvd.o \
./opencv/cxtables.o \
./opencv/cxutils.o 

CPP_DEPS += \
./opencv/cvaccum.d \
./opencv/cvadapthresh.d \
./opencv/cvapprox.d \
./opencv/cvcalccontrasthistogram.d \
./opencv/cvcalcimagehomography.d \
./opencv/cvcalibinit.d \
./opencv/cvcalibration.d \
./opencv/cvcamshift.d \
./opencv/cvcanny.d \
./opencv/cvcolor.d \
./opencv/cvcondens.d \
./opencv/cvcontours.d \
./opencv/cvcontourtree.d \
./opencv/cvconvhull.d \
./opencv/cvconvolve.d \
./opencv/cvcorner.d \
./opencv/cvcornersubpix.d \
./opencv/cvderiv.d \
./opencv/cvdistransform.d \
./opencv/cvdominants.d \
./opencv/cvemd.d \
./opencv/cvfeatureselect.d \
./opencv/cvfloodfill.d \
./opencv/cvfundam.d \
./opencv/cvgeometry.d \
./opencv/cvhaar.d \
./opencv/cvhistogram.d \
./opencv/cvhough.d \
./opencv/cvimgwarp.d \
./opencv/cvkalman.d \
./opencv/cvlinefit.d \
./opencv/cvlkpyramid.d \
./opencv/cvmatchcontours.d \
./opencv/cvmoments.d \
./opencv/cvmorph.d \
./opencv/cvmotempl.d \
./opencv/cvoptflowbm.d \
./opencv/cvoptflowhs.d \
./opencv/cvoptflowlk.d \
./opencv/cvpgh.d \
./opencv/cvposit.d \
./opencv/cvprecomp.d \
./opencv/cvpyramids.d \
./opencv/cvpyrsegmentation.d \
./opencv/cvrotcalipers.d \
./opencv/cvsamplers.d \
./opencv/cvshapedescr.d \
./opencv/cvsmooth.d \
./opencv/cvsnakes.d \
./opencv/cvsubdivision2d.d \
./opencv/cvsumpixels.d \
./opencv/cvswitcher.d \
./opencv/cvtables.d \
./opencv/cvtemplmatch.d \
./opencv/cvthresh.d \
./opencv/cvundistort.d \
./opencv/cvutils.d \
./opencv/cxalloc.d \
./opencv/cxarithm.d \
./opencv/cxarray.d \
./opencv/cxcmp.d \
./opencv/cxconvert.d \
./opencv/cxcopy.d \
./opencv/cxdatastructs.d \
./opencv/cxdrawing.d \
./opencv/cxdxt.d \
./opencv/cxerror.d \
./opencv/cxjacobieigens.d \
./opencv/cxlogic.d \
./opencv/cxlut.d \
./opencv/cxmathfuncs.d \
./opencv/cxmatmul.d \
./opencv/cxmatrix.d \
./opencv/cxmean.d \
./opencv/cxmeansdv.d \
./opencv/cxminmaxloc.d \
./opencv/cxnorm.d \
./opencv/cxouttext.d \
./opencv/cxpersistence.d \
./opencv/cxprecomp.d \
./opencv/cxrand.d \
./opencv/cxsumpixels.d \
./opencv/cxsvd.d \
./opencv/cxtables.d \
./opencv/cxutils.d 


# Each subdirectory must supply rules for building sources it contributes
opencv/%.o: ../opencv/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C++ Compiler'
	g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o"$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


